title: КЕГЭ 2
description: >-
  Отсортированные прототипы ЕГЭ по информатике по каждому заданию —
  с разборами, ответами и видеоразборами.
url: https://kege2.ru
lang: ru

plugins:
  - jekyll-sitemap
